-- ============================================================
-- ============================================================
TRUNCATE TABLE [DIM_DATE]
TRUNCATE TABLE [DIM_TIME] 
TRUNCATE TABLE [DIM_WEATHER] 
TRUNCATE TABLE [DIM_ILLUMINATION] 
TRUNCATE TABLE [DIM_COLLISIONTYPE] 
TRUNCATE TABLE [DIM_HARMFULEVENT]
TRUNCATE TABLE [DIM_OFFICER] 
TRUNCATE TABLE [DIM_PRECINCT] 
TRUNCATE TABLE [DIM_ZIPCODE] 
TRUNCATE TABLE [DIM_LOCATION]
TRUNCATE TABLE [FACT_ACCIDENT]

-- 1. DIM_DATE
-- ============================================================
CREATE TABLE [DIM_DATE] (
    DATE_KEY      INT IDENTITY(1,1) PRIMARY KEY,
    FULL_DATE     DATE NOT NULL,
    DAY_OF_WEEK   VARCHAR(20) NOT NULL,
    MONTH_NAME    VARCHAR(20) NOT NULL,
    QUARTER_NAME  VARCHAR(10) NOT NULL,
    YEAR          INT NOT NULL
);  

TRUNCATE TABLE [DIM_DATE] 
SELECT * FROM [DIM_DATE]
GO

-- ============================================================
-- 2. DIM_TIME
-- ============================================================
CREATE TABLE [DIM_TIME] (
    TIME_KEY     INT IDENTITY(1,1) PRIMARY KEY,
    HOUR         INT NOT NULL,
    MINUTE       INT NOT NULL,
    TIME_OF_DAY  VARCHAR(20) NOT NULL
);


SELECT * FROM [DIM_TIME]
TRUNCATE TABLE [DIM_TIME]
GO

-- ============================================================
-- 3. DIM_WEATHER
-- ============================================================
CREATE TABLE [DIM_WEATHER] (
    WEATHER_KEY         INT IDENTITY(1,1) PRIMARY KEY,
    WEATHER_DESCRIPTION  VARCHAR(255) NOT NULL
);

ALTER TABLE [DIM_WEATHER] ALTER COLUMN WEATHER_DESCRIPTION VARCHAR(255) NULL;
GO

SELECT * FROM DIM_WEATHER
TRUNCATE TABLE DIM_WEATHER
-- ============================================================
-- 4. DIM_ILLUMINATION
-- ============================================================
CREATE TABLE [DIM_ILLUMINATION] (
    ILLUMINATION_KEY          INT IDENTITY(1,1) PRIMARY KEY,
    ILLUMINATION              VARCHAR(255)
);

ALTER TABLE [DIM_ILLUMINATION] ALTER COLUMN ILLUMINATION VARCHAR(255) NULL;
SELECT * FROM DIM_ILLUMINATION
TRUNCATE TABLE DIM_ILLUMINATION 
GO

-- ============================================================
-- 5. DIM_COLLISIONTYPE
-- ============================================================
CREATE TABLE [DIM_COLLISIONTYPE] (
    COLLISION_TYPE_KEY          INT IDENTITY(1,1) PRIMARY KEY,
    COLLISION_TYPE_DESCRIPTION  VARCHAR(255) 
);
ALTER TABLE [DIM_COLLISIONTYPE] ALTER COLUMN COLLISION_TYPE_DESCRIPTION VARCHAR(255) NULL;
GO
SELECT * FROM [DIM_COLLISIONTYPE]

-- ============================================================
-- 6. DIM_HARMFULEVENT
-- ============================================================
CREATE TABLE [DIM_HARMFULEVENT] (
    HARMFUL_EVENT_KEY   INT IDENTITY(1,1) PRIMARY KEY,
    HARMFUL_CODE        VARCHAR(50) NULL,
    HARMFUL_DESCRIPTION VARCHAR(255) NOT NULL
);
ALTER TABLE [DIM_HARMFULEVENT] ALTER COLUMN HARMFUL_DESCRIPTION VARCHAR(255) NULL;
GO
SELECT * FROM [DIM_HARMFULEVENT]

-- ============================================================
-- 7. DIM_OFFICER
-- ============================================================
CREATE TABLE [DIM_OFFICER] (
    OFFICER_KEY            INT IDENTITY(1,1) PRIMARY KEY,
    REPORTING_OFFICER_ID   VARCHAR(50) NOT NULL
);
GO
SELECT * FROM [DIM_OFFICER]
-- ============================================================
-- 8. DIM_PRECINCT  (tạo trước Dim_Location vì sẽ được tham chiếu tới)
-- ============================================================
CREATE TABLE [DIM_PRECINCT] (
    PRECINCT_KEY   INT IDENTITY(1,1) PRIMARY KEY,
    PRECINCT_NAME  VARCHAR(50) NOT NULL
);
GO
SELECT * FROM [DIM_PRECINCT]
-- ============================================================
-- 9. DIM_ZIPCODE  (tạo trước Dim_Location vì sẽ được tham chiếu tới)
-- ============================================================
CREATE TABLE [DIM_ZIPCODE] (
    ZIP_CODE_KEY  INT IDENTITY(1,1) PRIMARY KEY,
    ZIP_CODE      VARCHAR(10) NOT NULL,
    CITY_NAME     VARCHAR(100) NULL,
    STATE         VARCHAR(10) NULL
);
GO
SELECT * FROM DIM_ZIPCODE
-- ============================================================
-- 10. DIM_LOCATION
-- ============================================================
CREATE TABLE [DIM_LOCATION] (
    LOCATION_KEY    INT IDENTITY(1,1) PRIMARY KEY,
    STREET_ADDRESS  VARCHAR(200) NOT NULL,
    ZIP_CODE_KEY    INT NOT NULL,
    PRECINCT_KEY    INT NOT NULL
);
SELECT * FROM DIM_LOCATION

ALTER TABLE [DIM_LOCATION] ADD CONSTRAINT FK_LOCATION_ZIPCODE  FOREIGN KEY (ZIP_CODE_KEY)  REFERENCES DIM_ZIPCODE(ZIP_CODE_KEY)
ALTER TABLE [DIM_LOCATION] ADD CONSTRAINT FK_LOCATION_PRECINCT FOREIGN KEY (PRECINCT_KEY)  REFERENCES DIM_PRECINCT(PRECINCT_KEY)
GO

-- ============================================================
-- 11. FACT_ACCIDENT
-- ============================================================
CREATE TABLE [FACT_ACCIDENT] (
    ACCIDENT_NUMBER        VARCHAR(50) PRIMARY KEY,
    DATE_KEY                INT NOT NULL,
    TIME_KEY                INT NOT NULL,
    LOCATION_KEY            INT NOT NULL,
    WEATHER_KEY              INT NOT NULL,
    ILLUMINATION_KEY        INT NOT NULL,
    COLLISION_TYPE_KEY      INT NOT NULL,
    HARMFUL_EVENT_KEY       INT NOT NULL,
    OFFICER_KEY              INT NOT NULL,
    NUM_MOTOR_VEHICLES      INT NULL,
    NUM_INJURIES             INT NULL,
    NUM_FATALITIES           INT NULL,
    PROPERTY_DAMAGE_FLAG    BIT NULL,
    HIT_AND_RUN_FLAG        BIT NOT NULL
);
GO

    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_DATE          FOREIGN KEY (DATE_KEY)          REFERENCES DIM_DATE(DATE_KEY)
    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_TIME          FOREIGN KEY (TIME_KEY)          REFERENCES DIM_TIME(TIME_KEY)
    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_LOCATION      FOREIGN KEY (LOCATION_KEY)      REFERENCES DIM_LOCATION(LOCATION_KEY)
    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_WEATHER       FOREIGN KEY (WEATHER_KEY)       REFERENCES DIM_WEATHER(WEATHER_KEY)
    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_ILLUMINATION  FOREIGN KEY (ILLUMINATION_KEY)  REFERENCES DIM_ILLUMINATION(ILLUMINATION_KEY)
    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_COLLISIONTYPE FOREIGN KEY (COLLISION_TYPE_KEY) REFERENCES DIM_COLLISIONTYPE(COLLISION_TYPE_KEY)
    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_HARMFULEVENT  FOREIGN KEY (HARMFUL_EVENT_KEY) REFERENCES DIM_HARMFULEVENT(HARMFUL_EVENT_KEY)
    ALTER TABLE [FACT_ACCIDENT] ADD CONSTRAINT FK_FACT_OFFICER       FOREIGN KEY (OFFICER_KEY)       REFERENCES DIM_OFFICER(OFFICER_KEY)

